[package]
name = "runity-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Software rasterizer for the runity engine. No dependencies."

[dependencies]
runity-math = { path = "../runity-math", version = "0.1.0" }
