//! A DEFLATE decoder (RFC 1951) and the zlib wrapper around it (RFC 1950).
//!
//! The encoder in [`crate::png`] only ever writes *stored* blocks, but reading
//! is a different job: a golden image regenerated by any other tool, or a
//! texture exported from an art package, is really compressed. So this is a
//! complete decoder — stored, fixed-Huffman and dynamic-Huffman blocks.
//!
//! The decoding loop follows the structure of zlib's own reference
//! implementation (`puff`): canonical Huffman codes are decoded bit by bit
//! against per-length symbol counts, which needs no lookup tables to build.

use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InflateError {
    /// The stream ended in the middle of a block.
    UnexpectedEnd,
    /// A code that is not in the Huffman tree, or a reserved block type.
    InvalidData(&'static str),
    /// A back-reference pointing before the start of the output.
    DistanceTooFar,
    /// The zlib header or its Adler-32 checksum did not check out.
    BadZlibStream(&'static str),
}

impl fmt::Display for InflateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            InflateError::UnexpectedEnd => write!(f, "compressed stream ended unexpectedly"),
            InflateError::InvalidData(what) => write!(f, "invalid deflate stream: {what}"),
            InflateError::DistanceTooFar => write!(f, "back-reference points before the output"),
            InflateError::BadZlibStream(what) => write!(f, "invalid zlib stream: {what}"),
        }
    }
}

impl std::error::Error for InflateError {}

type Result<T> = std::result::Result<T, InflateError>;

/// Reads bits least-significant-first, the order DEFLATE uses.
struct BitReader<'a> {
    data: &'a [u8],
    byte: usize,
    bit_buffer: u32,
    bit_count: u32,
}

impl<'a> BitReader<'a> {
    fn new(data: &'a [u8]) -> Self {
        Self {
            data,
            byte: 0,
            bit_buffer: 0,
            bit_count: 0,
        }
    }

    fn bits(&mut self, count: u32) -> Result<u32> {
        debug_assert!(count <= 24);
        while self.bit_count < count {
            let next = *self
                .data
                .get(self.byte)
                .ok_or(InflateError::UnexpectedEnd)?;
            self.byte += 1;
            self.bit_buffer |= (next as u32) << self.bit_count;
            self.bit_count += 8;
        }
        let value = self.bit_buffer & ((1u32 << count) - 1);
        self.bit_buffer >>= count;
        self.bit_count -= count;
        Ok(value)
    }

    /// Drop the partial byte, as stored blocks require.
    fn align_to_byte(&mut self) {
        let extra = self.bit_count % 8;
        self.bit_buffer >>= extra;
        self.bit_count -= extra;
    }

    fn read_aligned_bytes(&mut self, out: &mut Vec<u8>, count: usize) -> Result<()> {
        // Whole bytes may still be sitting in the bit buffer.
        for _ in 0..count {
            if self.bit_count >= 8 {
                out.push((self.bit_buffer & 0xff) as u8);
                self.bit_buffer >>= 8;
                self.bit_count -= 8;
            } else {
                let byte = *self
                    .data
                    .get(self.byte)
                    .ok_or(InflateError::UnexpectedEnd)?;
                self.byte += 1;
                out.push(byte);
            }
        }
        Ok(())
    }
}

/// A canonical Huffman code, stored as symbol counts per bit length.
struct Huffman {
    /// `counts[n]` = how many symbols use an `n`-bit code.
    counts: [u16; MAX_BITS + 1],
    /// Symbols ordered by code length, then by symbol value.
    symbols: Vec<u16>,
}

const MAX_BITS: usize = 15;

impl Huffman {
    fn new(lengths: &[u8]) -> Result<Self> {
        let mut counts = [0u16; MAX_BITS + 1];
        for &length in lengths {
            if length as usize > MAX_BITS {
                return Err(InflateError::InvalidData("code length above 15"));
            }
            counts[length as usize] += 1;
        }
        counts[0] = 0; // unused symbols

        // Offsets of each length's first symbol inside `symbols`.
        let mut offsets = [0u16; MAX_BITS + 2];
        for length in 1..=MAX_BITS {
            offsets[length + 1] = offsets[length] + counts[length];
        }

        let mut symbols = vec![0u16; lengths.iter().filter(|l| **l > 0).count()];
        for (symbol, &length) in lengths.iter().enumerate() {
            if length > 0 {
                symbols[offsets[length as usize] as usize] = symbol as u16;
                offsets[length as usize] += 1;
            }
        }
        Ok(Self { counts, symbols })
    }

    fn decode(&self, reader: &mut BitReader) -> Result<u16> {
        let mut code = 0i32;
        let mut first = 0i32;
        let mut index = 0i32;
        for length in 1..=MAX_BITS {
            code |= reader.bits(1)? as i32;
            let count = self.counts[length] as i32;
            if code - first < count {
                return Ok(self.symbols[(index + (code - first)) as usize]);
            }
            index += count;
            first = (first + count) << 1;
            code <<= 1;
        }
        Err(InflateError::InvalidData(
            "code not present in the Huffman tree",
        ))
    }
}

// RFC 1951 §3.2.5.
const LENGTH_BASE: [u16; 29] = [
    3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31, 35, 43, 51, 59, 67, 83, 99, 115, 131,
    163, 195, 227, 258,
];
const LENGTH_EXTRA: [u8; 29] = [
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0,
];
const DISTANCE_BASE: [u16; 30] = [
    1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193, 257, 385, 513, 769, 1025, 1537,
    2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577,
];
const DISTANCE_EXTRA: [u8; 30] = [
    0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13,
    13,
];
/// The order code-length codes are stored in (RFC 1951 §3.2.7).
const CODE_LENGTH_ORDER: [usize; 19] = [
    16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15,
];

fn fixed_tables() -> Result<(Huffman, Huffman)> {
    let mut literal_lengths = [0u8; 288];
    for (symbol, length) in literal_lengths.iter_mut().enumerate() {
        *length = match symbol {
            0..=143 => 8,
            144..=255 => 9,
            256..=279 => 7,
            _ => 8,
        };
    }
    Ok((Huffman::new(&literal_lengths)?, Huffman::new(&[5u8; 30])?))
}

fn dynamic_tables(reader: &mut BitReader) -> Result<(Huffman, Huffman)> {
    let literal_count = reader.bits(5)? as usize + 257;
    let distance_count = reader.bits(5)? as usize + 1;
    let code_length_count = reader.bits(4)? as usize + 4;
    if literal_count > 286 || distance_count > 30 {
        return Err(InflateError::InvalidData(
            "too many literal or distance codes",
        ));
    }

    let mut code_lengths = [0u8; 19];
    for &position in CODE_LENGTH_ORDER.iter().take(code_length_count) {
        code_lengths[position] = reader.bits(3)? as u8;
    }
    let code_length_table = Huffman::new(&code_lengths)?;

    // The literal and distance lengths are themselves Huffman-coded, with three
    // run-length escapes.
    let total = literal_count + distance_count;
    let mut lengths = vec![0u8; total];
    let mut index = 0;
    while index < total {
        let symbol = code_length_table.decode(reader)?;
        match symbol {
            0..=15 => {
                lengths[index] = symbol as u8;
                index += 1;
            }
            16 => {
                let previous =
                    *lengths
                        .get(index.wrapping_sub(1))
                        .ok_or(InflateError::InvalidData(
                            "repeat of a previous length with no previous length",
                        ))?;
                let repeat = 3 + reader.bits(2)? as usize;
                for _ in 0..repeat {
                    if index >= total {
                        return Err(InflateError::InvalidData("code length run overflows"));
                    }
                    lengths[index] = previous;
                    index += 1;
                }
            }
            17 | 18 => {
                let repeat = if symbol == 17 {
                    3 + reader.bits(3)? as usize
                } else {
                    11 + reader.bits(7)? as usize
                };
                if index + repeat > total {
                    return Err(InflateError::InvalidData("code length run overflows"));
                }
                index += repeat; // lengths are already zero
            }
            _ => return Err(InflateError::InvalidData("bad code length symbol")),
        }
    }

    Ok((
        Huffman::new(&lengths[..literal_count])?,
        Huffman::new(&lengths[literal_count..])?,
    ))
}

fn inflate_block(
    reader: &mut BitReader,
    out: &mut Vec<u8>,
    literals: &Huffman,
    distances: &Huffman,
) -> Result<()> {
    loop {
        let symbol = literals.decode(reader)? as usize;
        match symbol {
            0..=255 => out.push(symbol as u8),
            256 => return Ok(()), // end of block
            257..=285 => {
                let index = symbol - 257;
                let length =
                    LENGTH_BASE[index] as usize + reader.bits(LENGTH_EXTRA[index] as u32)? as usize;

                let distance_symbol = distances.decode(reader)? as usize;
                if distance_symbol >= DISTANCE_BASE.len() {
                    return Err(InflateError::InvalidData("distance symbol out of range"));
                }
                let distance = DISTANCE_BASE[distance_symbol] as usize
                    + reader.bits(DISTANCE_EXTRA[distance_symbol] as u32)? as usize;
                if distance > out.len() {
                    return Err(InflateError::DistanceTooFar);
                }

                // Copies may overlap — that is how runs are encoded — so this
                // has to go byte by byte.
                let start = out.len() - distance;
                for offset in 0..length {
                    let byte = out[start + offset];
                    out.push(byte);
                }
            }
            _ => return Err(InflateError::InvalidData("literal symbol out of range")),
        }
    }
}

/// Decode a raw DEFLATE stream.
pub fn inflate(data: &[u8]) -> Result<Vec<u8>> {
    let mut reader = BitReader::new(data);
    let mut out = Vec::new();
    loop {
        let final_block = reader.bits(1)? == 1;
        let block_type = reader.bits(2)?;
        match block_type {
            0 => {
                reader.align_to_byte();
                let mut header = Vec::with_capacity(4);
                reader.read_aligned_bytes(&mut header, 4)?;
                let length = u16::from_le_bytes([header[0], header[1]]);
                let complement = u16::from_le_bytes([header[2], header[3]]);
                if length != !complement {
                    return Err(InflateError::InvalidData(
                        "stored block length check failed",
                    ));
                }
                reader.read_aligned_bytes(&mut out, length as usize)?;
            }
            1 => {
                let (literals, distances) = fixed_tables()?;
                inflate_block(&mut reader, &mut out, &literals, &distances)?;
            }
            2 => {
                let (literals, distances) = dynamic_tables(&mut reader)?;
                inflate_block(&mut reader, &mut out, &literals, &distances)?;
            }
            _ => return Err(InflateError::InvalidData("reserved block type")),
        }
        if final_block {
            return Ok(out);
        }
    }
}

fn adler32(bytes: &[u8]) -> u32 {
    const MOD: u32 = 65521;
    let (mut a, mut b) = (1u32, 0u32);
    for chunk in bytes.chunks(5552) {
        for byte in chunk {
            a += *byte as u32;
            b += a;
        }
        a %= MOD;
        b %= MOD;
    }
    (b << 16) | a
}

/// Decode a zlib stream: two header bytes, deflate data, Adler-32 trailer.
pub fn zlib_decompress(data: &[u8]) -> Result<Vec<u8>> {
    if data.len() < 6 {
        return Err(InflateError::BadZlibStream("stream is too short"));
    }
    let (cmf, flg) = (data[0], data[1]);
    if cmf & 0x0f != 8 {
        return Err(InflateError::BadZlibStream("not a deflate stream"));
    }
    if (u16::from_be_bytes([cmf, flg])) % 31 != 0 {
        return Err(InflateError::BadZlibStream("header check failed"));
    }
    if flg & 0x20 != 0 {
        return Err(InflateError::BadZlibStream(
            "preset dictionaries are not supported",
        ));
    }

    let body = &data[2..data.len() - 4];
    let out = inflate(body)?;

    let expected = u32::from_be_bytes([
        data[data.len() - 4],
        data[data.len() - 3],
        data[data.len() - 2],
        data[data.len() - 1],
    ]);
    if adler32(&out) != expected {
        return Err(InflateError::BadZlibStream("Adler-32 mismatch"));
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `zlib.compress(b"hello hello hello hello", 9)` — a fixed-Huffman block
    /// with a back-reference, produced by a real zlib.
    const ZLIB_FIXED: &[u8] = &[
        0x78, 0xda, 0xcb, 0x48, 0xcd, 0xc9, 0xc9, 0x57, 0xc8, 0x40, 0x27, 0x01, 0x68, 0x03, 0x08,
        0xb1,
    ];

    /// `zlib.compress(b"a" * 32, 9)`: one literal plus a self-overlapping copy.
    const ZLIB_RUN: &[u8] = &[
        0x78, 0xda, 0x4b, 0x4c, 0xc4, 0x0f, 0x00, 0xc8, 0x30, 0x0c, 0x21,
    ];

    /// Weighted random text, which zlib compresses with a dynamic Huffman
    /// table (block type 2) — the path fixed-block vectors never reach.
    const ZLIB_DYNAMIC: &[u8] = include_bytes!("../tests/data/dynamic_huffman.zlib");
    const DYNAMIC_PLAINTEXT: &[u8] = include_bytes!("../tests/data/dynamic_huffman.txt");

    #[test]
    fn stored_blocks_round_trip() {
        // BFINAL=1, BTYPE=00, LEN=3, NLEN=!3, "abc"
        let stream = [0x01, 0x03, 0x00, 0xfc, 0xff, b'a', b'b', b'c'];
        assert_eq!(inflate(&stream).unwrap(), b"abc");
    }

    #[test]
    fn our_own_stored_stream_round_trips_through_the_decoder() {
        // The encoder and decoder are written independently of each other, so
        // this is a real round trip, not a tautology.
        let original: Vec<u8> = (0..200_000u32).map(|i| (i % 253) as u8).collect();
        let compressed = crate::png::zlib_stored(&original);
        assert!(compressed.len() > 65_535, "spans several stored blocks");
        assert_eq!(zlib_decompress(&compressed).unwrap(), original);
    }

    #[test]
    fn a_fixed_huffman_stream_from_zlib_decodes() {
        assert_eq!(
            zlib_decompress(ZLIB_FIXED).unwrap(),
            b"hello hello hello hello"
        );
    }

    #[test]
    fn a_dynamic_huffman_stream_from_zlib_decodes() {
        // Block type 2: the literal, distance and code-length tables all come
        // out of the stream itself.
        assert_eq!(
            ZLIB_DYNAMIC[2] >> 1 & 3,
            2,
            "the fixture must exercise dynamic Huffman"
        );
        assert_eq!(zlib_decompress(ZLIB_DYNAMIC).unwrap(), DYNAMIC_PLAINTEXT);
    }

    #[test]
    fn overlapping_back_references_expand_into_runs() {
        assert_eq!(zlib_decompress(ZLIB_RUN).unwrap(), b"a".repeat(32));
    }

    #[test]
    fn a_truncated_stream_is_an_error_not_a_panic() {
        assert_eq!(inflate(&[0x01, 0x03]), Err(InflateError::UnexpectedEnd));
        assert_eq!(
            zlib_decompress(&ZLIB_FIXED[..8]),
            Err(InflateError::UnexpectedEnd)
        );
    }

    #[test]
    fn corrupt_streams_are_rejected() {
        assert!(matches!(
            zlib_decompress(&[0x00, 0x00, 0, 0, 0, 0]),
            Err(InflateError::BadZlibStream(_))
        ));
        // A stored block whose length complement does not match.
        assert!(matches!(
            inflate(&[0x01, 0x03, 0x00, 0x00, 0x00, b'a', b'b', b'c']),
            Err(InflateError::InvalidData(_))
        ));
        // Reserved block type 3.
        assert!(matches!(
            inflate(&[0x07]),
            Err(InflateError::InvalidData(_))
        ));

        // A valid stream with its checksum flipped: the payload decodes, the
        // Adler-32 does not match.
        let mut tampered = ZLIB_FIXED.to_vec();
        *tampered.last_mut().unwrap() ^= 0xff;
        assert_eq!(
            zlib_decompress(&tampered),
            Err(InflateError::BadZlibStream("Adler-32 mismatch"))
        );
    }

    #[test]
    fn a_distance_before_the_output_start_is_rejected() {
        // A fixed-Huffman block whose first symbol is a copy from 7 bytes back,
        // with nothing decoded yet.
        assert_eq!(inflate(&[0x03, 0x52]), Err(InflateError::DistanceTooFar));
    }
}
