"""Write examples/valley/assets/models/tumbleweed.obj: a tumbleweed, a
ball of thin, curved, dry twigs half a metre across the radius.

Made here rather than taken from a kit, so it is CC0 like the rest of
the example's assets. Deterministic: the same seed, the same file.

    python3 tools/example-assets/tumbleweed.py
"""
import math
import pathlib
import random

RADIUS = 0.5
TWIGS = 140
SEGMENTS = 7
SIDES = 3


def norm(v):
    length = math.sqrt(sum(c * c for c in v)) or 1.0
    return tuple(c / length for c in v)


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def on_ball(rng, lo, hi):
    d = norm((rng.gauss(0, 1), rng.gauss(0, 1), rng.gauss(0, 1)))
    r = RADIUS * rng.uniform(lo, hi)
    return tuple(c * r for c in d)


def twig(rng):
    """Points along one twig: from near the core out and round the shell,
    bending as it goes."""
    start = on_ball(rng, 0.05, 0.5)
    end = on_ball(rng, 0.75, 1.0)
    bend = on_ball(rng, 0.6, 1.0)
    points = []
    for i in range(SEGMENTS + 1):
        t = i / SEGMENTS
        # A quadratic curve through a point on the shell: twigs arch.
        p = tuple(
            (1 - t) ** 2 * s + 2 * (1 - t) * t * b + t * t * e
            for s, b, e in zip(start, bend, end)
        )
        points.append(p)
    thick = rng.uniform(0.006, 0.014)
    return points, thick


def main():
    rng = random.Random(7)
    positions, normals, faces = [], [], []
    for _ in range(TWIGS):
        points, thick = twig(rng)
        rings = []
        for i, p in enumerate(points):
            ahead = points[min(i + 1, len(points) - 1)]
            behind = points[max(i - 1, 0)]
            along = norm(tuple(a - b for a, b in zip(ahead, behind)))
            side = norm(cross(along, (0.3, 1.0, 0.2)))
            up = cross(along, side)
            # Thinner toward the tip.
            r = thick * (1.0 - 0.7 * i / SEGMENTS)
            ring = []
            for k in range(SIDES):
                a = 2 * math.pi * k / SIDES
                n = tuple(math.cos(a) * s + math.sin(a) * u for s, u in zip(side, up))
                positions.append(tuple(c + r * m for c, m in zip(p, n)))
                normals.append(n)
                ring.append(len(positions))
            rings.append(ring)
        for a, b in zip(rings, rings[1:]):
            for k in range(SIDES):
                k2 = (k + 1) % SIDES
                faces.append((a[k], b[k], b[k2]))
                faces.append((a[k], b[k2], a[k2]))
    out = pathlib.Path(__file__).resolve().parents[2] / "examples/valley/assets/models/tumbleweed.obj"
    lines = [
        "# tumbleweed.obj — перекати-поле: клубок сухих веток",
        "# Generated by tools/example-assets/tumbleweed.py; CC0.",
    ]
    lines += ["v %.5f %.5f %.5f" % p for p in positions]
    lines += ["vn %.4f %.4f %.4f" % n for n in normals]
    lines += ["f %d//%d %d//%d %d//%d" % (a, a, b, b, c, c) for a, b, c in faces]
    out.write_text("\n".join(lines) + "\n")
    print(f"{out}: {len(positions)} vertices, {len(faces)} triangles")


if __name__ == "__main__":
    main()
