[package]
name = "runity-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Entity storage, scheduling and the main loop of the runity engine."

[dependencies]
runity-math = { path = "../runity-math", version = "0.1.0" }
runity-render = { path = "../runity-render", version = "0.1.0" }
runity-physics = { path = "../runity-physics", version = "0.1.0" }
runity-platform = { path = "../runity-platform", version = "0.1.0" }
